version: '3'
services:
  keycloak:
    image: jboss/keycloak:9.0.0
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
    networks:
      - keycloak
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - "-c"
      - "standalone.xml"
  post_process:
    build: .
    image: adorsys/keycloak-config-cli:latest
    depends_on:
      - keycloak
    networks:
      - keycloak
    volumes:
      - ./contrib/example-config:/config
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - WAIT_TIME_IN_SECONDS=120
      - SPRING_PROFILES_INCLUDE=debug
      - IMPORT_FORCE=false

networks:
  keycloak:
