version: '3.1'
services:
  keycloak:
    image: jboss/keycloak:4.8.1.Final
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
    ports:
    - "8080:8080"
    - "8787:8787"
    command:
    - "-b"
    - "0.0.0.0"
    - "--debug"
  post_process:
    build: .
    image: adorsys.de/keycloak-config-cli:latest
    depends_on:
    - keycloak
    links:
    - keycloak
    volumes:
    - ./example-config:/tmp/keycloak-config-cli/configs
    environment:
    - KEYCLOAK_URL=http://keycloak:8080
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin123
    - SPRING_PROFILES_INCLUDE=debug
    command: config-cli
