keycloak:
  url: http://localhost:8080
  password: admin123

import:
  path: ./example-config

logging:
  level:
    de.adorsys.keycloak.config.service.RealmImportService: debug
    de.adorsys.keycloak.config.service.AuthenticationFlowsImportService: debug
    de.adorsys.keycloak.config.service.ExecutionFlowImportService: debug
